In [2]:
import numpy as np
import time

In [2]:
arr= np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [7]:
#  Execution performance Python list vs Numpy Array
size=10_000_000
# time measure python list
python_list=list(range(size))
start_time= time.time() # will give us a start time
sq_list=[x**2 for x in python_list]
end_time=time.time()
print(f"for python list : start time:{end_time-start_time} ")

np_array=np.array(python_list)
start_time= time.time() # will give us a start time
#  vectorization 
sq_array=np_array ** 2 

end_time=time.time()
print(f"for Numpy list  :  time:{end_time-start_time}")


for python list : start time:3.5674636363983154 
for Numpy list  :  time:0.025208234786987305


In [8]:
# memory occupied by both
import sys
print(f"python list size {sys.getsizeof(python_list) * len(python_list) } bytes")
print(f"Numpy Array size {np_array.nbytes } bytes")


python list size 800000560000000 bytes
Numpy Array size 80000000 bytes


In [7]:
#  Creating Numpy Array from list
#  Arrays are homogeneous in numpy 
arar= np.array([1,2,3,4,5])
print(arar,type(arar), arar.dtype, arar.shape)
arar2= np.array([1,2,3,4,5,'prime'])
print(arar2,type(arar2), arar2.dtype, arar2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)


In [12]:
two_d=np.array([[1,3,5],[2,4,6],[1,2,3]])
print(f"three dimentional array :\n {two_d}\n and type of array : {two_d.dtype} and Shape : \n{two_d.shape}")

three dimentional array :
 [[1 3 5]
 [2 4 6]
 [1 2 3]]
 and type of array : int64 and Shape : 
(3, 3)


In [21]:
#  uisng built in functions creating numpy array
array_0= np.zeros((2,3), dtype="int64") # array created m*n 2*3 with values 0
print(array_0, array_0.shape)

array_1= np.ones((2,3), dtype="int64") # array created m*n 2*3 with values 1
print(array_1, array_1.shape)

array_f= np.full((2,3), 15) # array created m*n 2*3 with values 15
print(array_f, array_f.shape)

array_e= np.eye((3)) # array created m*n 2*3 with values identity matrix
print(array_e, array_e.shape)

#  arranage is like range in python parameter (start, end, step)

array_1= np.arange(1,11,2) # range elements
print(array_1, array_1.shape)

array_1= np.linspace(1,100,4) #  evenly spaced array  (start , end , size)
print(array_1, array_1.shape)


[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[15 15 15]
 [15 15 15]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 3 5 7 9] (5,)
[  1.  34.  67. 100.] (4,)


In [27]:
# properties of Array
np_aray=np.array([[1,2,3,4,5],[2,4,6,8,10],[1,3,5,7,9]])
print(np_aray.shape) # dimensions of array
print(np_aray.size) # total elements  of  an array
print(np_aray.dtype) # datatype of array
print(np_aray.ndim) # total number of dimensions of array

float_array=np_aray.astype(np.float64) # type casting in array
print(float_array)


(3, 5)
15
int64
2
[[ 1.  2.  3.  4.  5.]
 [ 2.  4.  6.  8. 10.]
 [ 1.  3.  5.  7.  9.]]


In [31]:
# Operation in Numpy Array
random_array=np.array([[1,2,3,],[2,4,6]])
print(random_array,random_array.shape)
reshaped_array= random_array.reshape((3,2)) # new dimension should be passed
print(reshaped_array,reshaped_array.shape)

falttend_array= random_array.flatten() # 2d array into 1 d array
print(falttend_array, falttend_array.shape)


[[1 2 3]
 [2 4 6]] (2, 3)
[[1 2]
 [3 2]
 [4 6]] (3, 2)
[1 2 3 2 4 6] (6,)


In [56]:
# Normal indexing on array
random_array=np.array([1,2,3,4,5])
print(random_array[0]) # 1
print(random_array[2]) # 3
for i in random_array:
    print(i, end=",")
print("")
twod_array=np.array([[1,2,3,],[2,4,6]])
print(twod_array[1][2])
print(twod_array[0][1])

#  Fancy indexing on np arrar
values=np.array([1,2,3,4,5])
index=[0,1,3]
print(values[index])
# Boolaen indexing
print(values[values%2==0])  # based on condition

# Slicing in  NP Array
print(values[1:4]) # (start end, step)
print(values[1:])
print(values[:4])
print(values[::-1]) 
print(values[-4:-1])
print(values[::2]) # step 
print(values[::3])

#  python list for slicing a copy of array is created but
# in np array a view is created 
#  means subpart of origional array not copy of array is created
#  Extra memory create nhi hoti

# Copy vs View
python_list=[1,2,3,4,5]
sub_list=python_list[0:3]
print(sub_list)
sub_list[1]=200
print(f" sublist :{sub_list}")
print(f" Origional list: {python_list}") 
print("for np array")
np_array= np.array(python_list)
sub_list=np_array[0:3]
copy_array=np_array[0:3].copy() # copying the view of slicing array

print(sub_list)
sub_list[1]=200
print(f" subarray in numpy :{sub_list}")
print(f" Origional array: {np_array}") 
print(f" copy of array : {copy_array}")


1
3
1,2,3,4,5,
6
2
[1 2 4]
[2 4]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[5 4 3 2 1]
[2 3 4]
[1 3 5]
[1 4]
[1, 2, 3]
 sublist :[1, 200, 3]
 Origional list: [1, 2, 3, 4, 5]
for np array
[1 2 3]
 subarray in numpy :[  1 200   3]
 Origional array: [  1 200   3   4   5]
 copy of array : [1 2 3]


In [2]:
#  Data Typs in numpy
#  type casting and  downCasting

nums= np.array([1,2,3,4,5])
print(nums,nums.dtype)

[1 2 3 4 5] int64


In [5]:
arr=np.array([2+3j])
arr1=np.array([4+4j])
print(arr+arr1)

[6.+7.j]


In [13]:
# Axes in Multidimentional Array
arr_2d= np.array([[1,2,3],[2,4,6],[1,3,5]])
print(arr_2d)
# sum of 2d array
print(np.sum(arr_2d))
#  sum of columns
sum_of_columns=np.sum(arr_2d,axis=0)
print(f"sum of columns {sum_of_columns}")

sum_of_rows=np.sum(arr_2d,axis=1)
print(f"sum of rows {sum_of_rows}")
# slicing
print(arr_2d[0:2,1:2])
      

[[1 2 3]
 [2 4 6]
 [1 3 5]]
27
sum of columns [ 4  9 14]
sum of rows [ 6 12  9]
[[2]
 [4]]


In [18]:
# 3d Array 2 x 3 x 2 depth * rows * column
arr_3d=np.array([[[1,2],[3,4],[4,5]],[[2,4],[1,3],[5,6]]])
print(arr_3d , arr_3d.shape)
#  indexing
print(arr_3d[0,1,1])
print(arr_3d[1,1,0])
#  slicing 
print(arr_3d[:,0,:]) # first row from both layers
print(arr_3d[:,:,0]) # first col of both layer


[[[1 2]
  [3 4]
  [4 5]]

 [[2 4]
  [1 3]
  [5 6]]] (2, 3, 2)
4
1
[[3 4]
 [1 3]]


In [4]:
#  Vectorization and broadcasting
#  Vectorization is the process of performing operations on an entire array at once instead of using loops.

# Create an array
arr = np.array([1, 2, 3, 4, 5])

# Add 10 to every element
result = arr + 10

print(result)

# Broadcasting is a NumPy feature that allows arrays of different shapes to perform arithmetic 
# operations without explicitly making their sizes equal.NumPy automatically expands the smaller 
# array to match the larger one.

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

result = matrix + vector

print(result)
#  Vector normalization : an array so that transforming it values so thEY
#  fil into its specific scale
  #  FORMULA: (X-MEAN)/S.D
  #  FORMULA FOR S.D: Root ((val(i)-mean)^2 /N (total number of values))

# standard normalization [each value of array - mean]/ S.D

arr = np.array([10, 20, 30, 40, 50])
mean = np.mean(arr)
std = np.std(arr)
normalized = (arr - mean) / std
print("Original Array:", arr)
print("Mean:", mean)
print("Standard Deviation:", std)
print("Normalized Array:", normalized)

arr1= np.array([[1,2],[3,4]])
mean=np.mean(arr1)
std=np.std(arr1)
normalized_arr= (arr - mean) / std
print(normalized_arr)



[11 12 13 14 15]
[[11 22 33]
 [14 25 36]]
Original Array: [10 20 30 40 50]
Mean: 30.0
Standard Deviation: 14.142135623730951
Normalized Array: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
[ 6.70820393 15.65247584 24.59674775 33.54101966 42.48529157]


In [8]:
#  Mathematical Functions
#  aggreggation function
arr= np.array([1,2,3,4,5])
print(np.sum(arr)) # sum 15
print(np.prod(arr)) # sproduct 120
print(np.min(arr) )
print(np.max(arr))
print(np.argmin(arr)) # will return the index of min value
print(np.argmax(arr)) # will return the index of max value
print(np.mean(arr))
print(np.std(arr) )
print(np.median(arr)) # arrange array in sorted ordr then middle value
print(np.var(arr)) # (xi-mean)^2 / N
      

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [9]:

#    power functions 
arr= np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4)) # pow(arr, power_value)
# Log related functions
print(np.log(arr)) # natural log
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr)) # e^x for e-> exp()


[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1  16  81 256 625]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [14]:
#  for rounding

arr= np.array([1,2,3,4,5,4,5,8])
print(np.round(3.14))
print(np.ceil(3.1))
print(np.floor(3.65))
print(np.trunc(3.14))

# unique 
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) # absolute value -ve will be into +ve 


3.0
4.0
3.0
3.0
[1 2 3 4 5 8]
