In [1]:
import torch
import torch.nn as nn

In [2]:
# input
torch.manual_seed(42)# same neural network will be created
inputs=torch.tensor([1.0,2.0,3.0]) # multidimentional array

In [ ]:
# 0d- dimentional
# 1d- vector
# 2d- matrix
# 3d- tensors images , video

In [3]:
neuron= nn.Linear(in_features=3,out_features=1)

In [4]:
output=neuron(inputs)

In [5]:
output

tensor([1.8097], grad_fn=<ViewBackward0>)

In [8]:
# Verify  apply the formula
tested_output=neuron.weight@inputs+neuron.bias


In [9]:
print(output)
print(tested_output)

tensor([1.8097], grad_fn=<ViewBackward0>)
tensor([1.8097], grad_fn=<AddBackward0>)
